version: 1
accounts:
- name: alice
  coins:
  - 1500000000000stake
  - 1000000000000000uatom
  - 1000000000000000uusd
  mnemonic: guard cream sadness conduct invite crumble clock pudding hole grit liar
    hotel maid produce squeeze return argue turtle know drive eight casino maze host
- name: bob
  coins:
  - 1000000000000stake
  - 1000000000000000uatom
  - 1000000000000000uusd
  mnemonic: friend excite rough reopen cover wheel spoon convince island path clean
    monkey play snow number walnut pull lock shoot hurry dream divide concert discover
client:
  typescript:
    path: ts-client
genesis:
  app_state:
    gov:
      deposit_params:
        min_deposit:
        - amount: "1"
          denom: stake
      voting_params:
        voting_period: 30s
validators:
- name: alice
  bonded: 5000000000stake
